language: php

matrix:
  include:
    - php: 7.2
      env: dependencies=lowest
    - php: 7.2
      env: dependencies=highest
    - php: 7.3
      env: dependencies=lowest
    - php: 7.3
      env: dependencies=highest

before_script:
  - echo 'Europe/Zurich' | sudo tee /etc/timezone
  - echo 'date.timezone = "Europe/Zurich"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update -q
  - if [ -z "$dependencies" ]; then composer install; fi;
  - if [ "$dependencies" = "highest" ]; then composer update -n; fi;
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest -n; fi;

script:
  - vendor/bin/phpunit --coverage-text --verbose
  - vendor/bin/infection --threads=$(nproc) --min-msi=100 --min-covered-msi=100 --verbose
  - vendor/bin/phpstan analyse
  - vendor/bin/phploc src --verbose
  - vendor/bin/php-cs-fixer fix --dry-run --stop-on-violation
  - if [ -z "$dependencies" ]; then vendor/bin/phpinsights analyse --no-interaction --min-quality=95; fi;
  - if [ "$dependencies" = "highest" ]; then vendor/bin/phpinsights analyse --no-interaction --min-quality=95; fi;
  - if [ "$dependencies" = "lowest" ]; then vendor/bin/phpinsights analyse --no-interaction --min-quality=95 --disable-security-check; fi;

