language: php

matrix:
  include:
    - php: 7.2
      env: dependencies=lowest
    - php: 7.2
    - php: 7.3
      env: dependencies=lowest
    - php: 7.3
    - php: 7.4
      env: dependencies=lowest
    - php: 7.4

before_script:
  - echo 'extension=apcu.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/apcu.ini
  - echo 'Europe/Zurich' | sudo tee /etc/timezone
  - echo 'date.timezone = "Europe/Zurich"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update -q
  - composer global require hirak/prestissimo
  - if [ -z "$dependencies" ]; then composer update -n; fi;
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest -n; fi;

script:
  - composer test

after_success:
  - travis_retry php vendor/bin/php-coveralls --coverage_clover=build/phpunit/phpunit.clover.xml --json_path=build/coveralls.json -v
