language: php

matrix:
  include:
    - php: 7.2
      env: dependencies=lowest
    - php: 7.2
      env: dependencies=highest
    - php: 7.3
      env: dependencies=lowest
    - php: 7.3
      env: dependencies=highest
    - php: 7.4snapshot
      env: dependencies=lowest
    - php: 7.4snapshot
      env: dependencies=highest
  allow_failures:
    - php: 7.4snapshot

before_script:
  - echo 'Europe/Zurich' | sudo tee /etc/timezone
  - echo 'date.timezone = "Europe/Zurich"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update -q
  - composer global require hirak/prestissimo
  - if [ -z "$dependencies" ]; then composer install; fi;
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest -n; fi;
  - if [ "$dependencies" = "highest" ]; then composer update -n; fi;

script:
  - composer test
